<?php
declare(strict_types=1);

use App\Controllers\AuthController;
use App\Controllers\DashboardController;
use App\Controllers\TicketController;
use App\Controllers\UserController;
use App\Controllers\ReportController;
use App\Controllers\SettingsController;
use App\Controllers\HealthController;
use App\Controllers\NotificationController;
use App\Controllers\SdwanPublicController;
use App\Controllers\SecurityController;

return [
	'GET' => [
		'/' => [DashboardController::class, 'index'],
		'/login' => [AuthController::class, 'loginForm'],
		'/sdwan/cadastro' => [SdwanPublicController::class, 'form'],
		'/sdwan/enderecos' => [SdwanPublicController::class, 'storeAddresses'],
		'/acupad/cadastro' => [SdwanPublicController::class, 'form'],
		'/acupad/enderecos' => [SdwanPublicController::class, 'storeAddresses'],
		'/two-factor' => [AuthController::class, 'twoFactorForm'],
		'/auditoria' => [AuthController::class, 'auditoria'],
		'/logout' => [AuthController::class, 'logout'],
		'/change-password-first' => [AuthController::class, 'changePasswordFirst'],
		'/health' => [HealthController::class, 'index'],
		'/dashboard/dailies' => [DashboardController::class, 'dailyStats'],
		'/dashboard/summary' => [DashboardController::class, 'summaryStats'],
		'/dashboard/daily-destinations' => [DashboardController::class, 'dailyDestinationStats'],
		'/dashboard/status-stats' => [DashboardController::class, 'statusStats'],
		'/dashboard/credit-usage' => [DashboardController::class, 'creditUsageStats'],
		'/dashboard/charts-bundle' => [DashboardController::class, 'chartsBundle'],
		'/dashboard/tickets-open' => [DashboardController::class, 'ticketsOpen'],
		'/dashboard/inventory-stats' => [DashboardController::class, 'inventoryStats'],
		'/dashboard/inventory-download' => [DashboardController::class, 'downloadInventoryFile'],
		'/dashboard/purchased-dailies' => [DashboardController::class, 'purchasedDailiesStats'],
		'/dashboard/purchased-dailies-download' => [DashboardController::class, 'downloadPurchasedDailiesFile'],
		'/dashboard/sdwan-entries' => [DashboardController::class, 'sdwanEntries'],
		'/dashboard/sdwan-entries/chart' => [DashboardController::class, 'sdwanChartStats'],
		'/dashboard/sdwan-entries/export/pdf' => [DashboardController::class, 'sdwanExportPdf'],
		'/dashboard/sdwan-entries/export/xlsx' => [DashboardController::class, 'sdwanExportXlsx'],
		'/dashboard/sdwan-entries/image' => [DashboardController::class, 'sdwanEntryImage'],
		'/dashboard/sdwan-access-link' => [DashboardController::class, 'sdwanAccessLinkStatus'],
		'/dashboard/sdwan-access-link/qr' => [DashboardController::class, 'sdwanAccessLinkQr'],
		'/dashboard/sdwan-audit' => [DashboardController::class, 'sdwanAuditLogs'],
		'/dashboard/sdwan-import/template' => [DashboardController::class, 'sdwanImportTemplate'],
		'/dashboard/enderecos' => [DashboardController::class, 'storeAddresses'],
		'/tickets' => [TicketController::class, 'index'],
		'/tickets/view' => [TicketController::class, 'show'],
		'/tickets/attachments' => [TicketController::class, 'attachments'],
		'/tickets/attachment-download' => [TicketController::class, 'downloadAttachment'],
		'/users' => [UserController::class, 'index'],
		'/users/credit-history' => [UserController::class, 'creditHistory'],
		'/reports/pdf' => [ReportController::class, 'pdf'],
		'/reports/xlsx' => [ReportController::class, 'xlsx'],
		'/reports/csv' => [ReportController::class, 'csv'],
		'/settings/maintenance' => [SettingsController::class, 'maintenanceStatus'],
		'/settings' => [SettingsController::class, 'index'],
		'/notifications' => [NotificationController::class, 'index'],
		'/security/two-factor' => [SecurityController::class, 'status'],
	],
	'POST' => [
		'/login' => [AuthController::class, 'login'],
		'/sdwan/cadastro' => [SdwanPublicController::class, 'submit'],
		'/acupad/cadastro' => [SdwanPublicController::class, 'submit'],
		'/two-factor' => [AuthController::class, 'twoFactorVerify'],
		'/change-password-first-update' => [AuthController::class, 'updatePasswordFirst'],
		'/tickets/create' => [TicketController::class, 'create'],
		'/tickets/update' => [TicketController::class, 'update'],
		'/tickets/status' => [TicketController::class, 'updateStatus'],
		'/tickets/assign' => [TicketController::class, 'assignToMe'],
		'/tickets/response' => [TicketController::class, 'saveResponse'],
		'/tickets/update-technician' => [TicketController::class, 'updateTechnician'],
		'/tickets/delete' => [TicketController::class, 'delete'],
		'/tickets/attachment-delete' => [TicketController::class, 'deleteAttachment'],
		'/tickets/clone' => [TicketController::class, 'cloneTicket'],
		'/users/create' => [UserController::class, 'create'],
		'/users/update' => [UserController::class, 'update'],
		'/users/delete' => [UserController::class, 'delete'],
		'/users/credits' => [UserController::class, 'adjustCredits'],
		'/users/credits/reset' => [UserController::class, 'resetCredits'],
		'/users/credit-history/clear' => [UserController::class, 'clearCreditHistory'],
		'/dashboard/inventory-upload' => [DashboardController::class, 'uploadInventoryFile'],
		'/dashboard/purchased-dailies-upload' => [DashboardController::class, 'uploadPurchasedDailiesFile'],
		'/dashboard/sdwan-entries/create' => [DashboardController::class, 'sdwanEntryCreate'],
		'/dashboard/sdwan-entries/update' => [DashboardController::class, 'sdwanEntryUpdate'],
		'/dashboard/sdwan-entries/delete' => [DashboardController::class, 'sdwanEntryDelete'],
		'/dashboard/sdwan-access-link/generate' => [DashboardController::class, 'sdwanAccessLinkGenerate'],
		'/dashboard/sdwan-access-link/revoke' => [DashboardController::class, 'sdwanAccessLinkRevoke'],
		'/dashboard/sdwan-settings' => [DashboardController::class, 'sdwanSettingsUpdate'],
		'/dashboard/sdwan-import' => [DashboardController::class, 'sdwanImportCsv'],
		'/dashboard/sdwan-stores/upload' => [DashboardController::class, 'sdwanUploadStores'],
		'/dashboard/sdwan-cleanup' => [DashboardController::class, 'sdwanCleanup'],
		'/settings/maintenance' => [SettingsController::class, 'maintenanceToggle'],
		'/settings/update' => [SettingsController::class, 'update'],
		'/notifications/read' => [NotificationController::class, 'markRead'],
		'/notifications/read-all' => [NotificationController::class, 'markAllRead'],
		'/security/two-factor/setup' => [SecurityController::class, 'setup'],
		'/security/two-factor/confirm' => [SecurityController::class, 'confirm'],
		'/security/two-factor/disable' => [SecurityController::class, 'disable'],
	],
];
